# SPDX-FileCopyrightText: : 2017-2024 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#run
run:
  prefix: "2030-targets"
  name: 
    - targets+pci-pmi
    - targets+pci-pmi-national-h2-expansion
    - targets+greenfield-infra
    - targets+no-infra
    - only-emission-targets+no-infra
  scenarios:
    enable: true
    file: config/scenarios.pci-pmi.yaml
  disable_progressbar: false
  shared_resources:
    policy: 2030-targets
    exclude: []
  shared_cutouts: true

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#foresight
foresight: overnight

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#scenario
# Wildcard docs in https://pypsa-eur.readthedocs.io/en/latest/wildcards.html
scenario:
  ll:
  - v1.05
  clusters:
  - 90
  opts:
  - ''
  sector_opts:
  - ''
  planning_horizons:
  - 2030

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#countries
countries: ['AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'ME', 'MK', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK', 'XK']

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#snapshots
snapshots:
  start: "2013-01-01"
  end: "2014-01-01"
  inclusive: 'left'

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#enable
enable:
  retrieve: true
  retrieve_databundle: true
  retrieve_cost_data: true
  build_cutout: false
  retrieve_cutout: true
  custom_busmap: false
  drop_leap_day: true

debug:
  solve_network_temp_reduction: false

solving:
  solver:
    name: gurobi
    options: gurobi-default   
  mem_mb: 150000 #memory in MB; 20 GB enough for 50+B+I+H2; 100 GB for 181+B+I+H2
  runtime: 24h #runtime in humanfriendly style https://humanfriendly.readthedocs.io/en/latest/